### PR TITLE
Add the ExternalTriggers to the c-sharp bindings

### PR DESCRIPTION
**Pull request by curds01**
1) Add the new menge c api functions to MengeWrapper.
2) Add the ExternalTrigger class.
3) Give an example of invoking triggers in the C# program.
4) Add release notes.

See https://github.com/MengeCrowdSim/Menge/pull/57

/cc @JimSEOW

### CODE REVIEW

**Comment by JimSEOW** [comment]
The link to the CS [EventTrigger Example](https://github.com/curds01/MengeCS/tree/external_events)

**Comment by MengeCrowdSim** [comment]
I'm about to push it to master. I just wanted to give you a chance to weigh in before doing so.  So, I'll go ahead and merge.

**Comment by JimSEOW** [comment]
I want to make sure whoever follow our discussion get the right .NET binding and example ASAP :-)

**Comment by MengeCrowdSim** [comment]
An excellent point.

**Pull request merged**
